### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by bambokianr** [bambokianr/finance-manager-mobile#4]
- [x] Implementar redux
- [x] Integração api com mobile (após implementação do redux)
- [ ] Lib gráfico (https://github.com/indiespirit/react-native-chart-kit)
- [ ] Integração google calendar (provavelmente tem que configurar deep linking).

------------------------------

Componente `Select`
- [x] Corrigir style - text
- [x] Registrar componente no Unform

------------------------------

Componente `InsertEditExpense`
- [x] Adicionar KeyboardAvoidingView, ScrollView
- [x] Corrigir input data
- [x] Criar componente checkbox

------------------------------

Componente `DatePicker`
- [ ] Impedir que teclado apareça

------------------------------
- [ ] Finalizar reducer = create e edit
